apiVersion: v1
kind: Service
metadata:
  name: fastapi-2-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: fastapi-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-2-deployment
  namespace: default
  labels:
    app: fastapi-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-2
  template:
    metadata:
      labels:
        app: fastapi-2
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: fastapi-2
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        # image: opentelemetry-python-test-be1
        ports:
        - containerPort: 80
