apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: default
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: fastapi
        # image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        image: opentelemetry-python-test-be1
        ports:
        - containerPort: 80
